---
- hosts: all
  vars:
    ansible_python_interpreter: auto_silent
  vars_files:
    vars/chezmoi.yml
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # seconds
      become: true
  tasks:
    - import_tasks: tasks/dotfiles.yml
