---
- hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: auto_silent
  vars_files:
    vars/chezmoi.yml
  pre_tasks:
    - name: Set effective_user (allows for local or remote execution)
      set_fact:
        effective_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
      tags: always
    - name: Set user_home (as $HOME may not be /home/$USER)
      set_fact:
        user_home: "{{ ansible_env.HOME }}"
      tags: always
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # seconds
      become: true
      tags: always
  tasks:
    - fail:
        msg: "Playbook was written for Debian OS family"
      when: ansible_os_family != 'Debian'

    - import_tasks: tasks/dotfiles.yml
      tags: dotfiles
    - import_tasks: tasks/zsh.yml
      tags: zsh
    - import_tasks: tasks/terminal.yml
      tags: terminal
    - import_tasks: tasks/neovim.yml
      tags: neovim
    - import_tasks: tasks/i3.yml
      tags: i3
    - import_tasks: tasks/docker.yml
      tags: docker

