- name: Install docker prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
    state: present
  become: true

- name: Ensure GPG directory exists
  file:
    path: "/home/{{ ansible_user }}/.gnupg"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700

- name: Initialize GPG keyring
  command: gpg --list-keys
  become_user: "{{ ansible_user }}"
  become: true
  changed_when: false

- name: Download docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    mode: 0644

- name: Verify docker GPG key
  command: gpg --dry-run --quiet --import --import-options import-show /tmp/docker.gpg
  register: gpg_import_result
  changed_when: false

- name: Fail if Docker GPG key is invalid
  fail:
    msg: "Invalid Docker GPG key"
  when: "'9DC858229FC7DD38854AE2D88D81803C0EBFCD88' not in gpg_import_result.stdout"

- name: Add Docker GPG key to keyring
  command: gpg --dearmor --batch --yes -o /usr/share/keyrings/docker-archive-keyring.gpg /tmp/docker.gpg
  become: true 

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
  become: true

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  become: true

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true

- name: Restart Docker service
  systemd:
    name: docker
    state: restarted
    enabled: true
  become: true

- name: Ensure Docker is running
  systemd:
    name: docker
    state: started
  become: true

