- name: Install dotfiles prerequisites
  apt:
    name:
      - age
      - curl
    state: present
  become: true

# There is no chezmoi apt package, so we install it this way...
- name: Install chezmoi dotfiles manager tool
  shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "{{ chezmoi_install_path }}"
  register: chezmoi_install_result
  failed_when:
    - chezmoi_install_result.rc != 0
    - "'info installed ' + chezmoi_install_full_path not in chezmoi_install_result.stdout"
    - not (chezmoi_install_full_path is file)

- name: Checkout dotfiles
  git:
    repo: https://github.com/akyidrian/dotfiles.git
    dest: "{{ chezmoi_source_path }}"
    accept_hostkey: yes
    force: yes

- name: Copy chezmoi key (used for encrypted dotfiles)
  copy:
    src: "chezmoi/{{ chezmoi_key_file_name }}"
    dest: "{{ chezmoi_key_full_path }}"
    owner: "{{ effective_user }}"
    group: "{{ effective_user }}"
    mode: 0600
    decrypt: yes

- name: Ensure chezmoi config directory exists
  file:
    path: "{{ chezmoi_config_path }}"
    state: directory
    mode: 0755
    owner: "{{ effective_user }}"
    group: "{{ effective_user }}"

- name: Copy chezmoi config file
  template:
    src: "chezmoi/{{ chezmoi_config_file_name }}.j2"
    dest: "{{ chezmoi_config_full_path }}"
    owner: "{{ effective_user }}"
    group: "{{ effective_user }}"
    mode: 0600

# Change occurs when anything is printed in verbose output
- name: Apply dotfiles
  command: "{{ chezmoi_install_full_path }} apply --force --verbose"
  register: chezmoi_apply_result
  changed_when: chezmoi_apply_result.stdout | trim != ''
