- name: Install neovim prerequisites
  apt:
    name: unzip
    state: present
  become: true

# FIXME: Assuming x64
- name: Download latest neovim release
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    dest: /tmp/nvim-linux64.tar.gz
    mode: 0644

- name: Remove existing neovim installation
  file:
    path: /opt/nvim
    state: absent
  become: true

- name: Extract neovim to /opt
  unarchive:
    src: /tmp/nvim-linux64.tar.gz
    dest: /opt
    remote_src: true
  become: true

- name: Create symbolic link for neovim
  file:
    src: "/opt/nvim-linux64/bin/nvim"
    dest: "/usr/local/bin/nvim"
    state: link
    force: yes
  become: true
