- name: Install gnome-terminal
  apt:
    name: gnome-terminal
    state: present
  become: true
- name: Set default terminal to gnome-terminal
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/gnome-terminal
    link: /usr/bin/x-terminal-emulator
  become: true
- name: Install Gogh dependencies
  apt:
    name:
      - dconf-cli
      - uuid-runtime
    state: present
  become: true
- name: Clone Gogh repository
  git:
    repo: https://github.com/Gogh-Co/Gogh.git
    dest: ~/ansible/gogh
- name: Install Tokyo Night theme
  shell: ~/ansible/gogh/installs/tokyo-night.sh
  environment:
    TERMINAL: gnome-terminal
  become: true
  become_user: "{{ ansible_user }}"
- name: Ensure the fonts directory exists
  file:
    path: ~/.local/share/fonts
    state: directory
    mode: 0755
- name: Download RobotoMono
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/RobotoMono.zip
    dest: ~/.local/share/fonts/RobotoMono.zip
    mode: 0644
- name: Install unzip 
  apt:
    name: unzip
    state: present
  become: true
- name: Unzip RobotoMono
  unarchive:
    src: ~/.local/share/fonts/RobotoMono.zip 
    dest: ~/.local/share/fonts
    remote_src: yes
- name: Update font cache
  shell: fc-cache ~/.local/share/fonts
  register: fc_cache_result
  changed_when: fc_cache_result.rc == 0
- name: Ensure RobotoMono font is available
  shell: fc-list | grep -i roboto
  register: fc_list_result
  changed_when:
    - fc_list_result.rc == 0
    - fc_list_result.stdout_lines | length > 0
- name: Load dconf settings for GNOME terminal
  shell: dconf load /org/gnome/terminal/ < ~/.gnome-terminal.dconf 
  become_user: "{{ ansible_user }}"
  become: true

